query beers($offset: String, $filter: String, $filter_low: String, $direction: SortOperationKind!) {
  beers(
    first: 10
    after: $offset
    order_by: { name: $direction }
    where: { OR: [{name_contains: $filter}, {name_contains: $filter_low}] }
  ) {
    edges {
      cursor
      node {
        name
        slug
        averageGrade
        breweries {
          name
        }
        styles {
          name
        }
      }
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}